// Generated from Rust declarations. Regenerate with cargo run -p snenkbot_desktop --example export_contracts -- frontend/src/lib/contracts.

// This file has been generated by Specta. Do not edit this file manually.
export type ActionChoices = {
	action_id: string,
	field_id: string,
	/**  Current literal value of the dependency declared by this field's schema. */
	depends_on: string | null,
};

/**  Editor defaults come from the same Rust input type used by the capability. */
export type ActionDefinition = {
	schema: ConfigSchema,
	defaults: { [key in string]: unknown },
};

export type ApplyEditorEdit = {
	session_id: string,
	expected_revision: number,
	edit: EditorOperation,
};

export type ApproveTwitchLogin = {
	attempt_id: string,
	user_id: string,
};

export type AuthenticationError = {
	code: AuthenticationErrorCode,
	message: string,
};

export type AuthenticationErrorCode = "stale_attempt" | "not_ready" | "busy" | "unavailable";

export type AuthenticationIdentity = {
	attempt_id: string,
};

export type CallBinding = { Explicit: {
	inputs: { [key in string]: Input },
} } | "AllNamedArguments";

export type CompletedRun = {
	run_id: string,
	workflow_id: string,
	revision: number,
	outcome: Outcome,
};

export type Condition = ({ Equal: [Input, Input] }) & { All?: never; Any?: never; Contains?: never; Exists?: never; Greater?: never; Less?: never; Not?: never; NotEqual?: never; NullOrEmpty?: never } | ({ NotEqual: [Input, Input] }) & { All?: never; Any?: never; Contains?: never; Equal?: never; Exists?: never; Greater?: never; Less?: never; Not?: never; NullOrEmpty?: never } | ({ Exists: Input }) & { All?: never; Any?: never; Contains?: never; Equal?: never; Greater?: never; Less?: never; Not?: never; NotEqual?: never; NullOrEmpty?: never } | ({ NullOrEmpty: Input }) & { All?: never; Any?: never; Contains?: never; Equal?: never; Exists?: never; Greater?: never; Less?: never; Not?: never; NotEqual?: never } | ({ Contains: [Input, Input] }) & { All?: never; Any?: never; Equal?: never; Exists?: never; Greater?: never; Less?: never; Not?: never; NotEqual?: never; NullOrEmpty?: never } | ({ Less: [Input, Input] }) & { All?: never; Any?: never; Contains?: never; Equal?: never; Exists?: never; Greater?: never; Not?: never; NotEqual?: never; NullOrEmpty?: never } | ({ Greater: [Input, Input] }) & { All?: never; Any?: never; Contains?: never; Equal?: never; Exists?: never; Less?: never; Not?: never; NotEqual?: never; NullOrEmpty?: never } | ({ All: Condition[] }) & { Any?: never; Contains?: never; Equal?: never; Exists?: never; Greater?: never; Less?: never; Not?: never; NotEqual?: never; NullOrEmpty?: never } | ({ Any: Condition[] }) & { All?: never; Contains?: never; Equal?: never; Exists?: never; Greater?: never; Less?: never; Not?: never; NotEqual?: never; NullOrEmpty?: never } | ({ Not: Condition }) & { All?: never; Any?: never; Contains?: never; Equal?: never; Exists?: never; Greater?: never; Less?: never; NotEqual?: never; NullOrEmpty?: never };

export type ConfigChoice = {
	/**  Stable stored value. Labels may change without retargeting saved workflows. */
	value: string,
	label: string,
	detail: string | null,
};

export type ConfigChoiceSource = {
	/**  Namespaced key supplied by a compiled integration, such as `obs.scenes`. */
	key: string,
	/**  Input field whose current value narrows the available choices. */
	depends_on: string | null,
};

export type ConfigField = {
	id: string,
	label: string,
	description: string,
	introduced_in: number,
	kind: ConfigFieldKind,
	required: boolean,
	choice_source: ConfigChoiceSource | null,
};

export type ConfigFieldKind = "text" | "secret" | "integer" | "toggle";

export type ConfigOutput = {
	id: string,
	label: string,
	description: string,
	kind: ConfigOutputKind,
	required: boolean,
};

export type ConfigOutputKind = "text" | "number" | "toggle";

export type ConfigSchema = {
	id: string,
	version: number,
	title: string,
	fields: ConfigField[],
	outputs: ConfigOutput[],
};

export type ConfigurationError = {
	code: ConfigurationErrorCode,
	message: string,
};

export type ConfigurationErrorCode = "unavailable" | "busy" | "missing_session" | "stale_revision" | "invalid_values" | "save_conflict" | "save_failed" | "revision_exhausted";

export type ConfigurationSaveResult = {
	snapshot: ConfigurationSnapshot,
	notices: SaveNotice[],
};

export type ConfigurationSessionRequest = {
	session_id: string,
};

export type ConfigurationSnapshot = {
	session_id: string,
	revision: number,
	module: ConnectionModule,
	schema: ConfigSchema,
	defaults: { [key in string]: unknown },
	values: { [key in string]: unknown },
};

export type ConnectionModule = "obs" | "vtube_studio";

export type ConnectionState = "inactive" | "connecting" | "connected" | "error";

export type ConnectionStatus = {
	integration: string,
	connection: string,
	title: string,
	state: ConnectionState,
	detail: string,
};

export type CopyTwitchLogin = {
	attempt_id: string,
	target: TwitchCopyTarget,
};

export type CreateWorkflow = {
	name: string,
};

export type CredentialPresence = "empty" | "stored" | "unavailable";

export type DesktopBatch = {
	updates: DesktopUpdate[],
	/**  A slow consumer must refresh its snapshot before applying further updates. */
	resync_required: boolean,
};

export type DesktopEvent = { event: "lifecycle"; payload: StartupState } | { event: "inventory"; payload: WorkflowStatus[] } | { event: "connections"; payload: {
	connections: ConnectionStatus[],
	requests: ReconfigurationRequest[],
} } | { event: "engine"; payload: Event } | { event: "run_completed"; payload: CompletedRun } | { event: "input"; payload: InputEvent } | { event: "twitch_authentication"; payload: TwitchAuthentication } | { event: "error_added"; payload: ErrorNotice } | { event: "error_dismissed"; payload: {
	id: string,
} };

export type DesktopSnapshot = {
	sequence: number,
	startup: StartupState,
	workflows: WorkflowStatus[],
	connections: ConnectionStatus[],
	reconfiguration_requests: ReconfigurationRequest[],
	errors: ErrorNotice[],
	last_completed: CompletedRun | null,
	pending_input: InputRequest | null,
	twitch_authentication: TwitchAuthentication | null,
};

export type DesktopUpdate = {
	sequence: number,
	event: DesktopEvent,
};

export type DismissError = {
	id: string,
};

export type EditorError = {
	code: EditorErrorCode,
	message: string,
};

export type EditorErrorCode = "unavailable" | "busy" | "missing_session" | "stale_revision" | "revision_exhausted" | "invalid_edit" | "workflow_unavailable" | "save_conflict" | "save_failed";

export type EditorOperation = { operation: "rename"; name: string } | { operation: "enabled"; enabled: boolean } | { operation: "set_input"; step_id: string; field_id: string; value: Input } | { operation: "insert_at"; kind: StepKind; destination: StepDestination; position: StepPosition } | { operation: "set_kind"; step_id: string; kind: StepKind } | { operation: "remove"; step_id: string } | { operation: "move_to"; step_id: string; destination: StepDestination; position: StepPosition } | { operation: "trigger_enabled"; trigger_id: string; enabled: boolean } | { operation: "trigger_kind"; trigger_id: string; kind: TriggerKind } | { operation: "append_trigger"; kind: TriggerKind } | { operation: "insert_trigger_at"; kind: TriggerKind; position: TriggerPosition } | { operation: "remove_trigger"; trigger_id: string } | { operation: "move_trigger_to"; trigger_id: string; position: TriggerPosition } | { operation: "undo" } | { operation: "redo" };

export type EditorSaveResult = EditorSaveResult_Serialize | EditorSaveResult_Deserialize;

export type EditorSaveResult_Deserialize = {
	snapshot: EditorSnapshot_Deserialize,
	notices: SaveNotice[],
};

export type EditorSaveResult_Serialize = {
	snapshot: EditorSnapshot_Serialize,
	notices: SaveNotice[],
};

export type EditorSessionRequest = {
	session_id: string,
};

export type EditorSnapshot = EditorSnapshot_Serialize | EditorSnapshot_Deserialize;

export type EditorSnapshot_Deserialize = {
	session_id: string,
	revision: number,
	draft: WorkflowDefinition_Deserialize,
	dirty: boolean,
	can_undo: boolean,
	can_redo: boolean,
	saved_revision: number,
};

export type EditorSnapshot_Serialize = {
	session_id: string,
	revision: number,
	draft: WorkflowDefinition_Serialize,
	dirty: boolean,
	can_undo: boolean,
	can_redo: boolean,
	saved_revision: number,
};

export type EditorValueSources = {
	session_id: string,
	expected_revision: number,
	step_id: string,
};

export type ErrorNotice = {
	id: string,
	message: string,
};

export type Event = ({ StepStarted: {
	workflow_id: string,
	step_id: string,
} }) & { ActivationRejected?: never; StepFinished?: never; VariableReplaced?: never } | ({ StepFinished: {
	workflow_id: string,
	step_id: string,
	outcome: Outcome,
} }) & { ActivationRejected?: never; StepStarted?: never; VariableReplaced?: never } | ({ VariableReplaced: {
	workflow_id: string,
	step_id: string,
	name: string,
} }) & { ActivationRejected?: never; StepFinished?: never; StepStarted?: never } | ({ ActivationRejected: {
	workflow_id: string,
	revision: number,
	reason: string,
} }) & { StepFinished?: never; StepStarted?: never; VariableReplaced?: never };

export type Failure = {
	step_id: string,
	kind: FailureKind,
	message: string,
	remote_effect_uncertain: boolean,
};

export type FailureCategory = "definition" | "missing_value" | "invalid_type" | "capability" | "connector" | "action" | "timeout" | "input" | "limit" | "other";

export type FailureKind = "invalid_definition" | "missing_value" | "invalid_type" | "capability_unavailable" | "connector_unavailable" | "action" | "timeout" | "input" | "loop_limit" | "step_limit" | "call_depth" | "called_workflow" | "no_child_succeeded";

export type FailurePolicy = "Stop" | "Continue";

export type HistoryErrorCode = "busy" | "invalid_request" | "invalid_cursor" | "stale_cursor" | "unavailable" | "run_unavailable" | "corrupt_record";

export type HistoryFilter = {
	workflow_id: string | null,
	outcome: HistoryOutcome | null,
	trigger_kind: HistoryTriggerKind | null,
};

export type HistoryOutcome = "running" | "succeeded" | "stopped" | "cancelled" | "failed" | "rejected" | "interrupted";

export type HistoryPage = {
	entries: HistorySummary[],
	next_cursor: string | null,
};

export type HistoryQuery = {
	page_size?: number,
	cursor?: string | null,
	filter?: HistoryFilter,
};

export type HistoryQueryError = {
	code: HistoryErrorCode,
	message: string,
};

export type HistorySummary = { kind: "record"; summary: RunSummary } | { kind: "corrupt"; file_name: string; message: string };

export type HistoryTriggerKind = "manual" | "schedule" | "event" | "webhook";

export type Input = ({ Literal: unknown }) & { Array?: never; Object?: never; Reference?: never; Text?: never; Trigger?: never; Variable?: never } | ({ Object: { [key in string]: Input } }) & { Array?: never; Literal?: never; Reference?: never; Text?: never; Trigger?: never; Variable?: never } | ({ Array: Input[] }) & { Literal?: never; Object?: never; Reference?: never; Text?: never; Trigger?: never; Variable?: never } | ({ Reference: {
	step_id: string,
	output_id: string,
	fallback: Input | null,
} }) & { Array?: never; Literal?: never; Object?: never; Text?: never; Trigger?: never; Variable?: never } | ({ Trigger: {
	name: string,
	fallback: Input | null,
} }) & { Array?: never; Literal?: never; Object?: never; Reference?: never; Text?: never; Variable?: never } | ({ Variable: {
	name: string,
	fallback: Input | null,
} }) & { Array?: never; Literal?: never; Object?: never; Reference?: never; Text?: never; Trigger?: never } | ({ Text: TextPart[] }) & { Array?: never; Literal?: never; Object?: never; Reference?: never; Trigger?: never; Variable?: never };

export type InputBridgeError = { kind: "no_active_request" } | { kind: "stale_request" } | { kind: "busy" } | { kind: "emission_failed"; message: string };

export type InputEvent = { event: "requested"; payload: InputRequest } | { event: "changed"; payload: InputRequest } | { event: "closed"; payload: {
	request_id: string,
} };

export type InputField = {
	id: string,
	label?: string | null,
	default: Input | null,
	required: boolean,
	/**  Integration-owned validator key; its result becomes this field's output. */
	validator?: string | null,
};

export type InputRequest = {
	request_id: string,
	title: string,
	fields: InputField[],
	defaults: { [key in string]: unknown },
	values: { [key in string]: unknown },
	validating: boolean,
	error: string | null,
};

export type InputRequestIdentity = {
	request_id: string,
};

export type InspectHistory = {
	run_id: string,
};

export type OpenConfiguration = {
	module: ConnectionModule,
};

export type OpenEditor = {
	workflow_id: string,
};

export type Outcome = "Success" | "Stopped" | "Cancelled" | ({ Failed: Failure }) & { Rejected?: never } | ({ Rejected: string }) & { Failed?: never } | "Interrupted";

export type ReconfigurationRequest = {
	integration: string,
	connection: string,
	reason: string,
	affected_features: string[],
};

export type RunOutcome = { status: "running" } | { status: "succeeded" } | { status: "stopped" } | { status: "cancelled" } | { status: "failed"; category: FailureCategory } | { status: "rejected" } | { status: "interrupted" };

export type RunRecord = RunRecord_Serialize | RunRecord_Deserialize;

export type RunRecord_Deserialize = {
	run_id: string,
	workflow_id: string,
	workflow_revision: number,
	trigger: TriggerIdentity,
	/**  Milliseconds since the Unix epoch, UTC. */
	started_at_ms: number,
	/**  Milliseconds since the Unix epoch, UTC; absent while the run is active. */
	finished_at_ms: number | null,
	outcome: RunOutcome,
	/**  Script step IDs and outcomes only; script source and values stay private. */
	script_activity?: ScriptActivity[],
	/**  Typed execution steps for this run; no script source, values, or failure messages. */
	step_trace?: StepTrace[],
};

export type RunRecord_Serialize = {
	run_id: string,
	workflow_id: string,
	workflow_revision: number,
	trigger: TriggerIdentity,
	/**  Milliseconds since the Unix epoch, UTC. */
	started_at_ms: number,
	/**  Milliseconds since the Unix epoch, UTC; absent while the run is active. */
	finished_at_ms: number | null,
	outcome: RunOutcome,
	/**  Script step IDs and outcomes only; script source and values stay private. */
	script_activity?: ScriptActivity[],
	/**  Typed execution steps for this run; no script source, values, or failure messages. */
	step_trace?: StepTrace[],
};

/**  Run identity and outcome without the execution trace. */
export type RunSummary = {
	run_id: string,
	workflow_id: string,
	workflow_revision: number,
	trigger: TriggerIdentity,
	started_at_ms: number,
	finished_at_ms: number | null,
	outcome: RunOutcome,
};

export type RunWorkflow = {
	workflow_id: string,
};

export type SaveConfiguration = {
	session_id: string,
	expected_revision: number,
	values: { [key in string]: unknown },
};

export type SaveEditor = {
	session_id: string,
	expected_revision: number,
};

export type SaveNotice = "directory_sync" | "backup_retention";

export type SaveObsPassword = {
	password: string | null,
};

export type ScriptActivity = {
	workflow_id: string,
	step_id: string,
	outcome: ScriptOutcome,
};

export type ScriptOutcome = "succeeded" | "failed" | "cancelled";

export type StartTwitchLogin = {
	role: TwitchRole,
};

export type StartupState = { state: "starting" } | { state: "ready" } | { state: "closing" } | { state: "failed"; message: string };

export type Step = {
	id: string,
	on_failure: FailurePolicy,
	kind: StepKind,
};

/**  The child list that receives a new step. */
export type StepBranch = "Then" | "Else" | "Body";

/**  The sibling list at the root or inside one named container. */
export type StepDestination = "Root" | { Branch: {
	parent_id: string,
	branch: StepBranch,
} };

export type StepKind = ({ Action: {
	capability: string,
	version: number,
	inputs: { [key in string]: Input },
	deadline_ms: number | null,
} }) & { Call?: never; Delay?: never; If?: never; OneOrMore?: never; RequestInput?: never; SetVariable?: never; While?: never } | ({ SetVariable: {
	name: string,
	value: Input,
} }) & { Action?: never; Call?: never; Delay?: never; If?: never; OneOrMore?: never; RequestInput?: never; While?: never } | ({ If: {
	condition: Condition,
	then_steps: Step[],
	else_steps: Step[],
} }) & { Action?: never; Call?: never; Delay?: never; OneOrMore?: never; RequestInput?: never; SetVariable?: never; While?: never } | ({ While: {
	condition: Condition,
	steps: Step[],
} }) & { Action?: never; Call?: never; Delay?: never; If?: never; OneOrMore?: never; RequestInput?: never; SetVariable?: never } | ({ OneOrMore: {
	steps: Step[],
} }) & { Action?: never; Call?: never; Delay?: never; If?: never; RequestInput?: never; SetVariable?: never; While?: never } | ({ Delay: {
	millis: number,
} }) & { Action?: never; Call?: never; If?: never; OneOrMore?: never; RequestInput?: never; SetVariable?: never; While?: never } | ({ RequestInput: {
	title?: string | null,
	fields: InputField[],
} }) & { Action?: never; Call?: never; Delay?: never; If?: never; OneOrMore?: never; SetVariable?: never; While?: never } | ({ Call: {
	workflow_id: string,
	binding: CallBinding,
} }) & { Action?: never; Delay?: never; If?: never; OneOrMore?: never; RequestInput?: never; SetVariable?: never; While?: never } | "Stop";

/**  Direction for moving a step among its current siblings. */
export type StepMoveDirection = "Up" | "Down";

/**  Placement within a destination list, independent of changing array indices. */
export type StepPosition = "Append" |
/**
 *  Inserts immediately before this existing sibling. The ID must be unique
 *  across the workflow and belong to the chosen destination list.
 */
{ Before: {
	step_id: string,
} };

export type StepTrace = {
	/**  Monotonic within this run. Repeated loop executions get distinct numbers. */
	sequence: number,
	parent_sequence: number | null,
	workflow_id: string,
	workflow_revision: number,
	step_id: string,
	kind: StepTraceKind,
	started_at_ms: number,
	finished_at_ms: number,
	duration_ms: number,
	outcome: StepTraceOutcome,
};

export type StepTraceKind = { kind: "action"; capability: string; version: number } | { kind: "set_variable" } | { kind: "if" } | { kind: "while" } | { kind: "one_or_more" } | { kind: "delay" } | { kind: "request_input" } | { kind: "call"; workflow_id: string } | { kind: "stop" };

export type StepTraceOutcome = { status: "succeeded" } | { status: "stopped" } | { status: "cancelled" } | { status: "failed"; kind: FailureKind; remote_effect_uncertain: boolean; continued_by_policy: boolean };

export type SubmitInput = {
	request_id: string,
	values: { [key in string]: unknown },
};

export type TextPart = ({ Literal: string }) & { Value?: never } | ({ Value: Input }) & { Literal?: never };

export type TriggerDefinition = {
	id: string,
	enabled: boolean,
	kind: TriggerKind,
};

export type TriggerIdentity = {
	kind: HistoryTriggerKind,
	/**
	 *  A non-secret configured identity (for example, a schedule or webhook ID).
	 *  Do not put a payload, credential, URL, or user-provided value here.
	 */
	id: string | null,
};

/**  Event names are stable storage values, independent of connector runtime types. */
export type TriggerKind = { kind: "manual" } | { kind: "obs.recording_started" } | { kind: "obs.current_scene"; scene: string } | { kind: "integration_event"; integration: string; event: string; filters?: { [key in string]: unknown } };

/**  Trigger ordering is presentation order; every enabled matching trigger remains independent. */
export type TriggerPosition = "Append" | { Before: {
	trigger_id: string,
} };

/**  Account settings need only public identity, never credential-slot references or tokens. */
export type TwitchAccountSummary = {
	user_id: string,
	login: string,
};

export type TwitchAccountsSnapshot = {
	broadcaster: TwitchAccountSummary | null,
	bot: TwitchAccountSummary | null,
};

export type TwitchAuthentication = {
	attempt_id: string,
	role: TwitchRole,
	phase: TwitchAuthenticationPhase,
};

export type TwitchAuthenticationPhase = { state: "starting" } | { state: "code"; data: {
	url: string,
	code: string,
} } | { state: "review"; data: {
	login: string,
	user_id: string,
} } | { state: "saving" } | { state: "connected"; data: {
	login: string,
} } | { state: "failed"; data: {
	message: string,
} } | { state: "cancelled" };

export type TwitchCopyTarget = "link" | "code";

export type TwitchRole = "broadcaster" | "bot";

export type ValueSource = {
	source: ValueSourceKind,
	source_id: string,
	output_id: string,
	label: string,
	detail: string,
	optional: boolean,
	fallback_kind: string,
};

export type ValueSourceKind = "trigger" | "variable" | "step";

export type Workflow = {
	id: string,
	revision: number,
	overlap: boolean,
	steps: Step[],
	outputs: { [key in string]: Input },
};

export type WorkflowCategory = "Chat" | "Broadcast" | "Automation";

/**  The editable definition stored on disk. Execution remains independent of triggers. */
export type WorkflowDefinition = WorkflowDefinition_Serialize | WorkflowDefinition_Deserialize;

/**  The editable definition stored on disk. Execution remains independent of triggers. */
export type WorkflowDefinition_Deserialize = {
	enabled?: boolean,
	workflow: Workflow,
	triggers: TriggerDefinition[],
	name?: string | null,
};

/**  The editable definition stored on disk. Execution remains independent of triggers. */
export type WorkflowDefinition_Serialize = {
	enabled: boolean,
	workflow: Workflow,
	triggers: TriggerDefinition[],
	name?: string | null,
};

export type WorkflowStatus = {
	enabled: boolean,
	trigger_summary: string,
	step_count: number,
	category: WorkflowCategory,
	capabilities: string[],
	capability_titles: { [key in string]: string },
	/**  Direct action and trigger references, including disabled definitions. Labels never contain capability IDs. */
	integration_usage: { [key in string]: string[] },
	id: string,
	title: string,
	revision: number | null,
	has_steps: boolean,
	error: string | null,
};
